sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy-5.4.1
install:
    - pip install -U pip setuptools
    - pip install -U -e .[test] zope.testrunner
script:
    - zope-testrunner --test-path=src -v1j99
notifications:
    email: false
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
